# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template!

  Commit Guidelines - https://rakpart.testthedocs.org/commit-guidelines.html

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines.

  Commit Guidelines - https://rakpart.testthedocs.org/commit-guidelines.html

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! You are awesome !

# It is recommend to include as many gifs and emojis as possible

