site_name: Rakpart
site_description: 'Documentation Testing Tools'
site_author: 'TestTheDocs Community'
repo_name: 'testthedocs/rakpart'
repo_url: 'https://github.com/testthedocs/rakpart'
theme:
  name: 'material'
  logo: 'images/logo.svg'
  favicon: 'images/favicon.png'
  palette:
    primary: 'blue grey'
    accent: 'indigo'
    #  feature:
    #tabs: true

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.mark:

# Copyright
copyright: 'Copyright &copy; 2018 - TTD Community'

# Page tree
pages:
  - Home: index.md
