site_name: Rakpart
site_description: 'Rakpart Documentation - TestTheDocs Community'
site_author: 'TestTheDocs Community'
theme:
  name: 'material'
  logo: '_static/logo.svg'
  favicon: 'images/favicon.png'
  palette:
    primary: 'white'
    accent: 'green'
    #  feature:
    #tabs: true

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true

extra_css:
  - '_static/ttd.css'

# Repository
repo_name: testthedocs/rakpart
repo_url: https://github.com/testthedocs/rakpartvale
docs_dir: docs
edit_uri: edit/master/docs

# Copyright
copyright: 'Copyleft &copy; 2019 - TestTheDocs Community'

# Page tree
nav:
  - Home: index.md
  - Markup Languages: project_management/README.md
  - Contributing:
    - Code of Conduct: code-of-conduct.md
    - Commit Guidelines: commit-guidelines.md
    - Docker Guidelines: docker.md
